-- Discloses Meta Pixel Advanced Matching in the Privacy Policy's existing
-- "Sharing" section, which today only mentions delivery partners -- leaving
-- it as-is once Advanced Matching is turned on (Events Manager, not this
-- codebase) would be silently inaccurate about who we share data with and
-- why. The Cookies section already names Meta Pixel generically; this adds
-- the specific, more sensitive fact: hashed email/phone leaves the browser
-- for an advertising purpose, not just page-view analytics.
--
-- Guarded by `where value = to_jsonb(<old text>)` so this is a no-op if an
-- admin has since edited the Privacy policy away from the seeded default --
-- their edit is never silently overwritten. The old/new blocks below are
-- generated byte-for-byte from the live row (CRLF line endings and all),
-- not hand-typed, so the guard is guaranteed to match.

update public.store_settings
set value = to_jsonb($privacy_html$<p>TrendyMall ("we", "us") respects your privacy. This policy explains what information we collect when you use trendymall.lk, why we collect it, and how it's protected.</p>
<h2>Information We Collect</h2>
<p>When you create an account, place an order, or contact us, we collect:</p>
<ul>
<li>Your name, email address, and phone number</li>
<li>Your delivery address</li>
<li>Order history and the products you've purchased</li>
<li>Basic site-usage data (pages visited, general location) via Google Analytics and Meta Pixel, if enabled</li>
</ul>
<p>We do not collect or store your payment card details — card payments (when available) are processed securely by our payment partner, PayHere. Cash on Delivery and Bank Transfer orders are handled by us directly.</p>
<h2>How We Use Your Information</h2>
<ul>
<li>To process and deliver your orders</li>
<li>To send order confirmations and delivery updates</li>
<li>To respond to your questions and support requests</li>
<li>To send occasional marketing emails, only if you've subscribed to our newsletter — you can unsubscribe at any time</li>
<li>To improve our website and product range</li>
</ul>
<h2>How We Store and Protect It</h2>
<p>Your data is stored securely with Supabase, our database provider, which encrypts data in transit and at rest. Access to customer data is restricted to TrendyMall staff who need it to fulfil your order.</p>
<h2>Sharing</h2>
<p>We do not sell your personal information. We share the minimum necessary details (name, phone, address) with our delivery partners solely to deliver your order.</p>
<p>Where Meta Pixel's Advanced Matching is enabled, we also share a securely hashed version of your email address and/or phone number with Meta, to help measure and improve our advertising. This hashing happens automatically in your browser, through Meta's own technology, before anything is sent — we never send your personal information to Meta in plain text, and this only happens for information you've already entered into a form on our own site.</p>
<h2>Your Rights</h2>
<p>You can request a copy of the personal data we hold about you, ask us to correct it, or ask us to delete your account and associated data, by contacting us at <a href="mailto:trendy07mall@gmail.com">trendy07mall@gmail.com</a>.</p>
<h2>Cookies</h2>
<p>We use cookies and similar technologies for essential site functionality (like keeping items in your cart) and, where enabled, for analytics (Google Analytics) and advertising (Meta Pixel) to understand how our site is used and improve it.</p>
<h2>Changes to This Policy</h2>
<p>We may update this policy from time to time. Continued use of the site after changes means you accept the updated policy.</p>$privacy_html$::text),
    updated_at = now()
where key = 'policies.privacy_body'
  and value = to_jsonb($old_privacy_html$<p>TrendyMall ("we", "us") respects your privacy. This policy explains what information we collect when you use trendymall.lk, why we collect it, and how it's protected.</p>
<h2>Information We Collect</h2>
<p>When you create an account, place an order, or contact us, we collect:</p>
<ul>
<li>Your name, email address, and phone number</li>
<li>Your delivery address</li>
<li>Order history and the products you've purchased</li>
<li>Basic site-usage data (pages visited, general location) via Google Analytics and Meta Pixel, if enabled</li>
</ul>
<p>We do not collect or store your payment card details — card payments (when available) are processed securely by our payment partner, PayHere. Cash on Delivery and Bank Transfer orders are handled by us directly.</p>
<h2>How We Use Your Information</h2>
<ul>
<li>To process and deliver your orders</li>
<li>To send order confirmations and delivery updates</li>
<li>To respond to your questions and support requests</li>
<li>To send occasional marketing emails, only if you've subscribed to our newsletter — you can unsubscribe at any time</li>
<li>To improve our website and product range</li>
</ul>
<h2>How We Store and Protect It</h2>
<p>Your data is stored securely with Supabase, our database provider, which encrypts data in transit and at rest. Access to customer data is restricted to TrendyMall staff who need it to fulfil your order.</p>
<h2>Sharing</h2>
<p>We do not sell your personal information. We share the minimum necessary details (name, phone, address) with our delivery partners solely to deliver your order.</p>
<h2>Your Rights</h2>
<p>You can request a copy of the personal data we hold about you, ask us to correct it, or ask us to delete your account and associated data, by contacting us at <a href="mailto:trendy07mall@gmail.com">trendy07mall@gmail.com</a>.</p>
<h2>Cookies</h2>
<p>We use cookies and similar technologies for essential site functionality (like keeping items in your cart) and, where enabled, for analytics (Google Analytics) and advertising (Meta Pixel) to understand how our site is used and improve it.</p>
<h2>Changes to This Policy</h2>
<p>We may update this policy from time to time. Continued use of the site after changes means you accept the updated policy.</p>$old_privacy_html$::text);
